[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@safe-global/safe-core-protocol=lib/safe-core-protocol',
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@noir-zk=../noir-zk'
    ]

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
